In [3]:
import numpy as np

In [4]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.size

10

In [7]:
a.shape

(10,)

In [8]:
b = np.array([[0,1,2,3,4,5], [0,1,2,3,4,5], [0,1,2,3,4,5,]])
b

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [9]:
b.shape

(3, 6)

In [10]:
a.ndim # кол-во измерений

1

In [11]:
len(a.shape) # ndim

1

In [12]:
b.ndim

2

In [13]:
c = np.array([[0,1,3,4], [5,6,7,8]])
c

array([[0, 1, 3, 4],
       [5, 6, 7, 8]])

In [14]:
c.size

8

In [15]:
c.shape

(2, 4)

In [16]:
c.ndim

2

In [17]:
c2 = c.reshape((4,2))
c

array([[0, 1, 3, 4],
       [5, 6, 7, 8]])

In [18]:
c2

array([[0, 1],
       [3, 4],
       [5, 6],
       [7, 8]])

In [19]:
c[0][0] = 10
c

array([[10,  1,  3,  4],
       [ 5,  6,  7,  8]])

In [20]:
c2

array([[10,  1],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8]])

In [21]:
c3 = c2.copy()
c3

array([[10,  1],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8]])

In [22]:
c2[0][1] = 22
c2

array([[10, 22],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8]])

In [23]:
c3

array([[10,  1],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8]])

In [24]:
c.dtype

dtype('int64')

In [25]:
d = np.array([0,1,2,3], dtype=np.float32)
d

array([0., 1., 2., 3.], dtype=float32)

In [26]:
d.itemsize

4

In [27]:
ar1 = np.arange(10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.linspace(0,10,25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [29]:
np.geomspace(1,256,9)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256.])

In [30]:
np.random.rand(5,5)

array([[0.27969507, 0.96681742, 0.04784852, 0.5845614 , 0.54929808],
       [0.81219005, 0.96335428, 0.73907968, 0.89949765, 0.46109434],
       [0.65358834, 0.8509483 , 0.72926013, 0.52595657, 0.21274861],
       [0.57909501, 0.67304938, 0.98550383, 0.93725452, 0.59296163],
       [0.3526943 , 0.45406419, 0.34643524, 0.57916812, 0.02543021]])

In [31]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [37]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.save('a_ndarray', a)


In [40]:
a_ld = np.load('a_ndarray.npy')
a_ld

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# savez для схарнения несольких массивов 

In [59]:
arr = np.random.uniform(size=(4,7), low=0, high=20) 
x0 = (arr - np.min(arr))/(np.max(arr) - np.min(arr))
x0

array([[0.36817568, 0.83714443, 0.85976792, 0.97378576, 0.07252745,
        0.95177088, 0.41133398],
       [0.89161329, 0.20218407, 0.44723713, 0.50261778, 0.62403707,
        0.84756104, 0.52810389],
       [0.4988336 , 0.16323003, 0.        , 0.43738289, 0.19621972,
        1.        , 0.79009151],
       [0.45281029, 0.93001643, 0.38468869, 0.32911318, 0.02051988,
        0.35042432, 0.66938341]])

In [72]:
m = np.random.randint(size=(8, 10), low = 0, high = 10)
m

array([[2, 7, 5, 5, 0, 0, 5, 0, 1, 8],
       [9, 1, 4, 0, 9, 3, 3, 2, 7, 0],
       [4, 1, 0, 7, 2, 6, 6, 2, 7, 1],
       [1, 7, 1, 8, 3, 9, 4, 2, 7, 2],
       [3, 6, 4, 1, 7, 3, 3, 1, 2, 9],
       [0, 3, 3, 7, 6, 0, 4, 8, 0, 7],
       [6, 8, 0, 5, 3, 6, 0, 6, 2, 0],
       [6, 2, 7, 5, 7, 6, 9, 5, 4, 2]])

In [76]:
index = np.argmin(m.sum(axis=1))
index, sum(m[index])

(0, 33)