In [7]:
import numpy as np

def check_independence(probs):
    Y2 = np.zeros(2)  
    Y3 = np.zeros(3) 
    
    Y23 = np.zeros((2, 3))
    
    for x in range(1, 7):
        y2 = x % 2
        y3 = x % 3
        p = probs[x-1]
        
        Y2[y2] += p
        Y3[y3] += p
        Y23[y2, y3] += p
    
    is_independent = True
    for i in range(2):
        for j in range(3):
            if abs(Y23[i,j] - Y2[i]*Y3[j]) > 1e-10:
                is_independent = False
                
    return Y2, Y3, Y23, is_independent

probs1 = np.full(6, 1/6)
Y2_1, Y3_1, Y23_1, indep1 = check_independence(probs1)

A = 1 / sum(range(1, 7))  
probs2 = np.array([k*A for k in range(1, 7)])
Y2_2, Y3_2, Y23_2, indep2 = check_independence(probs2)

print("Случай 1 (равновероятные):")
print(f"P(Y2): {Y2_1}")
print(f"P(Y3): {Y3_1}")
print(f"Совместное распределение P(Y2,Y3):\n{Y23_1}")
print(f"Независимы: {indep1}\n")

print("Случай 2 (пропорциональные):")
print(f"P(Y2): {Y2_2}")
print(f"P(Y3): {Y3_2}")
print(f"Совместное распределение P(Y2,Y3):\n{Y23_2}")
print(f"Независимы: {indep2}")

Случай 1 (равновероятные):
P(Y2): [0.5 0.5]
P(Y3): [0.33333333 0.33333333 0.33333333]
Совместное распределение P(Y2,Y3):
[[0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667]]
Независимы: True

Случай 2 (пропорциональные):
P(Y2): [0.57142857 0.42857143]
P(Y3): [0.42857143 0.23809524 0.33333333]
Совместное распределение P(Y2,Y3):
[[0.28571429 0.19047619 0.0952381 ]
 [0.14285714 0.04761905 0.23809524]]
Независимы: False


# 2

In [2]:
import numpy as np
from itertools import product


X_values = np.arange(13)  
Y_values = np.arange(14)  
Z_values = np.array([3, 7])

X_prob = np.full(13, 1/13)
Y_prob = np.full(14, 1/14)
Z_prob = np.array([9/10, 1/10])

combinations = list(product(X_values, Y_values, Z_values))
probabilities = []

for x, y, z in combinations:
    prob = X_prob[x] * Y_prob[y] * (Z_prob[0] if z == 3 else Z_prob[1])
    probabilities.append((x + y + z, prob))


sum_prob = {}
for sum_val, prob in probabilities:
    sum_prob[sum_val] = sum_prob.get(sum_val, 0) + prob

 
prob_12 = sum_prob.get(12, 0)


most_probable_sum = max(sum_prob.items(), key=lambda x: x[1])

prob_12, most_probable_sum

(0.05274725274725277, (16, 0.0697802197802198))

# 3

In [3]:
import numpy as np

X_sum = np.arange(1, 14).sum()  
A = 1/X_sum

Y_sum = np.arange(1, 13).sum()  
B = 1/Y_sum

Z_sum = np.arange(1, 9).sum()  
C = 1/Z_sum

# Создаем массивы вероятностей
X_prob = np.arange(1, 14) * A
Y_prob = np.arange(1, 13) * B
Z_prob = np.arange(1, 9) * C

def all_different(x, y, z):
    return x != y and x != z and y != z

total_prob = 0
for x in range(1, 14):
    for y in range(1, 13):
        for z in range(1, 9):
            if all_different(x, y, z):
                total_prob += X_prob[x-1] * Y_prob[y-1] * Z_prob[z-1]

print(f"Вероятность того, что X, Y, Z примут разные значения: {total_prob}")

Вероятность того, что X, Y, Z примут разные значения: 0.783647975955668


# 4

In [5]:
from scipy.stats import binom

def calculate_probability():
    n = 40  
    p_positive = 0.98  
    p_negative = 1 - p_positive  
    
    total_prob = 0
    
    for k in range(0, n + 1, 2):  
        prob = binom.pmf(k, n, p_negative)
        total_prob += prob
    
    return total_prob

result = calculate_probability()
print(f"P(X1 * X2 * ... * X40 > 0) = {result}")

P(X1 * X2 * ... * X40 > 0) = 0.59768307577766
