# 1

In [10]:
from math import pi
def S(R):
    return pi * R **2

In [12]:
R1 = 3
R2 = 5
abs(S(R1)-S(R2))

50.26548245743669

# 2

In [34]:
def show_matrix(matrix):
    for i in range(len(matrix)):
        print(" ".join([str(j) for j in matrix[i]]))

Matrix = [[1,2,9],
          [1,2,3],
          [8,2,3]]
show_matrix(Matrix)

1 2 9
1 2 3
8 2 3


In [35]:
def Transp(matrix):
    t_matrix = [[0]*len(matrix) for _ in range(len(matrix[0]))]
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            t_matrix[j][i] = matrix[i][j]
    return t_matrix
show_matrix(Transp(Matrix))

1 1 8
2 2 2
9 3 3


In [1]:
from module18 import *
check_dot_on_line('y=2x', [0,0])

True

# 20

# 21

# 25


In [ ]:
class StringAnalyzer:
    def __init__(self, text: str):
        self.text = text
        self.length = self.calculate_length()
        self.word_count = self.calculate_word_count()
        
    def calculate_length(self) -> int:
        return len(self.text)
    
    def calculate_word_count(self) -> int:
        words = self.text.strip().split()
        return len(words)
    
    def __str__(self) -> str:
        return f"Текст: {self.text}\n Длина: {self.length}\n Количество слов: {self.word_count}"


In [2]:
text = "Привет мир!"
string_analyzer = StringAnalyzer(text)
string_analyzer.length

11

In [11]:
string_analyzer.word_count


2

In [14]:
str(string_analyzer)

'Текст: Привет мир!\nДлина: 11\nКоличество слов: 2'

# 26

In [7]:
class Money:
    def __init__(self, nominal: int, count: int):
        self.nominal = nominal
        self.count = count
        
    @property
    def total_sum(self) -> int:
        return self.nominal * self.count
    
    def display_info(self) -> None:
        print(f"Номинал купюры: {self.nominal} руб.")
        print(f"Количество купюр: {self.count} шт.")
        print(f"Общая сумма: {self.total_sum} руб.")
    
    def can_afford(self, price: int) -> bool:
        return self.total_sum >= price
    
    def calculate_items(self, price: int) -> int:
        if price <= 0:
            raise ValueError("Цена товара должна быть больше 0")
        return self.total_sum // price




In [8]:

wallet = Money(100, 10)

wallet.display_info()

Номинал купюры: 100 руб.
Количество купюр: 10 шт.
Общая сумма: 1000 руб.


In [9]:
wallet.can_afford(500)


True

In [10]:

wallet.calculate_items(100)

10

# 27

Создайте класс ТОВАР с методами, позволяющими вывести на экран информацию о товаре, а также определить, может ли приобрести товар покупатель, имеющий заданную сумму денег. Создайте дочерние классы ПРОДУКТ (название, цена, дата производства, срок годности), ПАРТИЯ (название, цена за штуку, количество штук, дата производства, срок годности), ТЕЛЕФОН (название, цена) со своими методами вывода информации на экран и определения соответствия заданной цене. Создайте список из  n  товаров, выведите полную информацию из базы на экран, а также организуйте поиск товара, который может приобрести покупатель, имеющий заданную сумму денег.

In [1]:
from datetime import datetime

class Item:
    def __init__(self, name: str, price: float):
        self.name = name
        self.price = price
    
    def display_info(self) -> None:
        print(f"Название: {self.name}")
        print(f"Цена: {self.price} руб.")
    
    def can_afford(self, money: float) -> bool:
        return money >= self.price

class Product(Item):
    def __init__(self, name: str, price: float, production_date: datetime, expiry_date: datetime):
        super().__init__(name, price)
        self.production_date = production_date
        self.expiry_date = expiry_date
    
    def display_info(self) -> None:
        super().display_info()
        print(f"Дата производства: {self.production_date.strftime('%d.%m.%Y')}")
        print(f"Срок годности: {self.expiry_date.strftime('%d.%m.%Y')}")

class Batch(Item):
    def __init__(self, name: str, price_per_unit: float, quantity: int, 
                 production_date: datetime, expiry_date: datetime):
        super().__init__(name, price_per_unit * quantity)
        self.price_per_unit = price_per_unit
        self.quantity = quantity
        self.production_date = production_date
        self.expiry_date = expiry_date
    
    def display_info(self) -> None:
        super().display_info()
        print(f"Цена за штуку: {self.price_per_unit} руб.")
        print(f"Количество: {self.quantity} шт.")
        print(f"Дата производства: {self.production_date.strftime('%d.%m.%Y')}")
        print(f"Срок годности: {self.expiry_date.strftime('%d.%m.%Y')}")

class Phone(Item):
    def __init__(self, name: str, price: float):
        super().__init__(name, price)

def find_affordable_items(items: list[Item], budget: float) -> list[Item]:
    return [item for item in items if item.can_afford(budget)]



In [4]:
items = [
    Product("Молоко", 80.0, 
            datetime(2025, 3, 1), datetime(2025, 3, 15)),
    Batch("Йогурт", 50.0, 10,
            datetime(2025, 3, 1), datetime(2025, 3, 10)),
    Phone("iPhone 15", 89990.0)
]

print("=== Все товары ===")
for item in items:
    item.display_info()
    print("-" * 30)

budget = 1000.0 
affordable_items = find_affordable_items(items, budget)

print(f"\n=== Товары доступные за {budget} руб. ===")
for item in affordable_items:
    item.display_info()
    print("-" * 30)

=== Все товары ===
Название: Молоко
Цена: 80.0 руб.
Дата производства: 01.03.2024
Срок годности: 15.03.2024
------------------------------
Название: Йогурт
Цена: 500.0 руб.
Цена за штуку: 50.0 руб.
Количество: 10 шт.
Дата производства: 01.03.2024
Срок годности: 10.03.2024
------------------------------
Название: iPhone 15
Цена: 89990.0 руб.
------------------------------

=== Товары доступные за 1000.0 руб. ===
Название: Молоко
Цена: 80.0 руб.
Дата производства: 01.03.2024
Срок годности: 15.03.2024
------------------------------
Название: Йогурт
Цена: 500.0 руб.
Цена за штуку: 50.0 руб.
Количество: 10 шт.
Дата производства: 01.03.2024
Срок годности: 10.03.2024
------------------------------


In [6]:
phones = [
    {'make': 'Nokia', 'model': 216, 'color': 'Black'}, 
    {'make': 'Mi Max', 'model': '2', 'color': 'Gold'}, 
    {'make': 'Samsung', 'model': 7, 'color': 'Blue'}
]

sorted_phones = sorted(phones, key=lambda x: x['make'])
print("Отсортированные телефоны:")
print(sorted_phones)

def find_anagrams(word: str, word_list: list[str]) -> list[str]:
    sorted_word = ''.join(sorted(word))
    return list(filter(lambda x: ''.join(sorted(x)) == sorted_word, word_list))

word = 'abcd'
words = ['bcda', 'abce', 'cbda', 'cbea', 'adcb']
anagrams = find_anagrams(word, words)
print("\nНайденные анаграммы:")
print(anagrams)

mixed_list = [19, 'red', 12, 'green', 'blue', 10, 'white', 'green', 1]

sorted_mixed = sorted(filter(lambda x: isinstance(x, int), mixed_list)) + \
               sorted(filter(lambda x: isinstance(x, str), mixed_list))

print("\nОтсортированный смешанный список:")
print(sorted_mixed)

Отсортированные телефоны:
[{'make': 'Mi Max', 'model': '2', 'color': 'Gold'}, {'make': 'Nokia', 'model': 216, 'color': 'Black'}, {'make': 'Samsung', 'model': 7, 'color': 'Blue'}]

Найденные анаграммы:
['bcda', 'cbda', 'adcb']

Отсортированный смешанный список:
[1, 10, 12, 19, 'blue', 'green', 'green', 'red', 'white']


In [1]:
from functools import reduce
import random

def process_lists(list1: list[int], list2: list[int]) -> list[tuple[int, int]]:
    return list(map(lambda x, y: (x + y, x - y), list1, list2))

list1 = [6, 5, 3, 9]
list2 = [0, 1, 7, 7]
result = process_lists(list1, list2)
print("Результат обработки списков:")
print(result)

numbers = [random.randint(1, 100) for _ in range(10)]
print("\nСгенерированный список:")
print(numbers)

even_numbers = sorted(filter(lambda x: x % 2 == 0, numbers))
print("\nОтфильтрованные четные числа:")
print(even_numbers)

sum_even = reduce(lambda x, y: x + y, even_numbers, 0)
print("\nСумма четных чисел:")
print(sum_even)

Результат обработки списков:
[(6, 6), (6, 4), (10, -4), (16, 2)]

Сгенерированный список:
[73, 36, 55, 90, 4, 41, 3, 45, 31, 14]

Отфильтрованные четные числа:
[4, 14, 36, 90]

Сумма четных чисел:
144


In [7]:
import functools
import inspect

def show_function_info(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        module_name = inspect.getmodule(func).__name__
        print(f"Вызвана функция: {func.__name__}")
        print(f"Определена в модуле: {module_name}")
        return func(*args, **kwargs)
    return wrapper

def default_params(**default_kwargs):
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            final_kwargs = default_kwargs.copy()
            final_kwargs.update(kwargs)
            return func(*args, **final_kwargs)
        return wrapper
    return decorator

@show_function_info
def greet(name):
    print(f"Привет, {name}!")

@default_params(greeting="Привет", punctuation="!")
def advanced_greet(name, greeting="Здравствуйте", punctuation="."):
    print(f"{greeting}, {name}{punctuation}")



print("Тест первого декоратора:")
greet("Алиса")
print("\nТест второго декоратора:")
advanced_greet("Боб") 
advanced_greet("Ева", greeting="Добрый день") 

Тест первого декоратора:
Вызвана функция: greet
Определена в модуле: __main__
Привет, Алиса!

Тест второго декоратора:
Привет, Боб!
Добрый день, Ева!


In [10]:
from itertools import permutations
from typing import Generator, List

def prime_numbers(limit: int) -> Generator[int, None, None]:
    """Генерирует простые числа до заданного предела"""
    def is_prime(n: int) -> bool:
        if n < 2:
            return False
        for i in range(2, int(n ** 0.5) + 1):
            if n % i == 0:
                return False
        return True
    
    for num in range(2, limit + 1):
        if is_prime(num):
            yield num

def book_arrangements(books: List[str]) -> Generator[tuple, None, None]:
    """Генерирует все возможные расположения книг"""
    yield from permutations(books)

def even_squares(start: int, end: int) -> list:
    """Создает список квадратов четных чисел в диапазоне"""
    return [x**2 for x in range(start, end + 1) if x % 2 == 0]

def is_palindrome(num: int) -> bool:
    """Проверяет, является ли число палиндромом"""
    return str(num) == str(num)[::-1]

def filter_palindromes(numbers: List[int]) -> list:
    """Фильтрует список, оставляя только числа-палиндромы"""
    return [num for num in numbers if is_palindrome(num)]



In [15]:
print("Простые числа до 20:")
for prime in prime_numbers(20):
    print(prime, end=" ")
print("\n")

books = ["Книга1", "Книга2", "Книга3"]
print("Варианты расположения книг:")
for arrangement in book_arrangements(books):
    print(arrangement)
print()

# Тест генератора квадратов четных чисел
start, end = 1, 10
squares = even_squares(start, end)
print(f"Квадраты четных чисел от {start} до {end}:")
print(squares)
print()


numbers = [121, 123, 555, 999, 1001, 1234]
palindromes = filter_palindromes(numbers)
print("Числа-палиндромы:")
print(palindromes)

Простые числа до 20:
2 3 5 7 11 13 17 19 

Варианты расположения книг:
('Книга1', 'Книга2', 'Книга3')
('Книга1', 'Книга3', 'Книга2')
('Книга2', 'Книга1', 'Книга3')
('Книга2', 'Книга3', 'Книга1')
('Книга3', 'Книга1', 'Книга2')
('Книга3', 'Книга2', 'Книга1')

Квадраты четных чисел от 1 до 10:
[4, 16, 36, 64, 100]

Числа-палиндромы:
[121, 555, 999, 1001]


In [16]:
import numpy as np

def find_closest_pair(arr: np.ndarray, R: float) -> tuple[int, int]:
    sums = arr[:-1] + arr[1:]
    closest_idx = np.abs(sums - R).argmin()
    
    return arr[closest_idx], arr[closest_idx + 1]

def find_column_with_most_duplicates(matrix: np.ndarray) -> int:
    max_duplicates = 0
    result_column = 0
    
    for col in range(matrix.shape[1]):
        unique, counts = np.unique(matrix[:, col], return_counts=True)
        max_count = counts.max()
        
        if max_count > max_duplicates:
            max_duplicates = max_count
            result_column = col
            
    return result_column

arr = np.array([10, 22, 28, 29, 30, 40])
R = 54
pair = find_closest_pair(arr, R)
print(f"Массив: {arr}")
print(f"Целевое число R: {R}")
print(f"Найденная пара: {pair}")
print(f"Их сумма: {sum(pair)}")
print()


matrix = np.array([
    [1, 2, 3, 2],
    [2, 2, 4, 2],
    [3, 2, 3, 5],
    [4, 2, 4, 2]
])
print("Матрица:")
print(matrix)
col_idx = find_column_with_most_duplicates(matrix)
print(f"Столбец с наибольшим количеством повторений: {col_idx}")
print(f"Элементы этого столбца: {matrix[:, col_idx]}")

Массив: [10 22 28 29 30 40]
Целевое число R: 54
Найденная пара: (28, 29)
Их сумма: 57

Матрица:
[[1 2 3 2]
 [2 2 4 2]
 [3 2 3 5]
 [4 2 4 2]]
Столбец с наибольшим количеством повторений: 1
Элементы этого столбца: [2 2 2 2]
